### PR TITLE
Not merge all scripts

### LINKED ISSUE #10: Using alias directives
When using "Using alias directives" like 
**using ResourcesKeys = xy.Common.Properties.ResourcesKeys;**
in combination with multiple scripts it results in an Exception "error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations."
Reason is that it seems that all scripts are merged into one file. All r# and using Statements are cut out except using alias directives. Leading to a script file where an using alias directive is in the middle of two classes.

### PR DESCRIPTION
**Pull request by beolutz**
Fix #10.
ExecuteScript called for every csx file to support using alias directives.
Now no script merging is performed anymore.

### CODE REVIEW

**Comment by laedit** [comment]
Thanks for the PR!

Some tests are [broken](https://ci.appveyor.com/project/laedit/scriptcs-mef/build/0.2.2-PullRequest.12+2.build.61/tests), can you fix it please?

In order to avoid any regression in existing scenario, can you add this as an option?
I was thinking at a `KeepScriptsSeparated` boolean property in `ScriptCsCatalogOptions` for example, false by default.

File: src/ScriptCs.ComponentModel.Composition/ScriptCsCatalogOptions.cs [hunk 1]
```diff
@@ -39,4 +44,4 @@ internal ScriptCsCatalogOptions OverridesNullByDefault()
             };
```
Comment (laedit) [inline src/ScriptCs.ComponentModel.Composition/ScriptCsCatalogOptions.cs:45]: A `KeepScriptsSeparated = KeepScriptsSeparated` line is missing to avoid the override of this property.

**Review by laedit — CHANGES_REQUESTED** [review]

**Comment by laedit** [comment]
Excellent, thanks!
There just a small modification to make, and could you please add some tests on the `KeepScriptsSeparated` property default / overrided value?

**Review by laedit — APPROVED** [review]
:+1:
